# Generated by Django 3.2.11 on 2022-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='image', upload_to='images'),
            preserve_default=False,
        ),
    ]
