# Generated by Django 4.0.1 on 2022-01-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0004_alter_order_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
