# Generated by Django 4.0.1 on 2022-02-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0005_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
