# Generated by Django 4.0.1 on 2022-02-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeup', '0008_customer_delete_shipping_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
